##################################################
## Customize
##################################################
homeassistant:
  customize:
    sensor.deluge_down_speed:
      icon: mdi:cloud-download
      friendly_name: "Download Speed"
    sensor.deluge_up_speed:
      icon: mdi:cloud-upload
      friendly_name: "Upload Speed"

##################################################
## Components/Sensors
##################################################
sensor:
  - platform: deluge
    host: !secret deluge_host
    port: 58846
    username: !secret deluge_username
    password: !secret deluge_password
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'
