##################################################
## Components/Sensors
##################################################
input_select:
  garage_motion_status:
    name: Garage Motion Status
    options:
      - idle
      - motion
    initial: motion

switch:
  - platform: mqtt
    name: "Sonoff Garage Light"
    state_topic: "stat/sonoff_garage_light/POWER"
    command_topic: "cmnd/sonoff_garage_light/POWER"
    availability_topic: "tele/sonoff_garage_light/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

sensor:
  - platform: template
    sensors:
      garage_motion_status:
        value_template: "{{ states.input_select.garage_motion_status.state }}"
        friendly_name: "Garage Motion Status"

##################################################
## Automation
##################################################
automation:
# When we detect motion, set status to Motion
  - alias: Garage motion detected
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_garage
        to: 'on'
      - platform: state
        entity_id: switch.sonoff_garage_light
        to: 'on'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.garage_motion_status
          option: 'motion'

# No Motion for 15 minutes, set to idle
  - alias: Garage no motion detected
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_garage
        to: 'off'
        for:
          minutes: 15
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.garage_motion_status
          option: 'idle'

  - alias: Garage light left on no motion
    trigger:
      - platform: state
        entity_id: sensor.garage_motion_status
        to: 'idle'
    condition:
      condition: state
      entity_id: switch.sonoff_garage_light
      state: 'on'
    action:
      - service: notify.martin
        data:
          title: "Garage Alert!"
          message: "Light left on. Turning off."
      - service: homeassistant.turn_off
        entity_id: switch.sonoff_garage_light

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.garage_motion_status

history:
  include:
    entities:
      - sensor.garage_motion_status
