##################################################
## Customize
##################################################
homeassistant:
  customize:
    sensor.external_ip:
      icon: mdi:ip-network-outline
      show_last_changed: true

##################################################
## Components/Sensors
##################################################
camera:
  - platform: generic
    still_image_url: "https://www.thinkbroadband.com/broadband/monitoring/quality/share/ae25a213af51ed64c2cdf601d17a934194317d36.png"
    name: broadbandquality

sensor:
# https://home-assistant.io/components/sensor.rest/
  - platform: rest
    resource: http://ip.jsontest.com
    name: External IP
    value_template: '{{ value_json.ip }}'

