##################################################
## Customize
##################################################
homeassistant:
  customize:
    sensor.owl_intuition_electricity_battery:
      friendly_name: Owl Battery
    sensor.owl_intuition_electricity_battery_level:
      friendly_name: Owl Battery Level
    sensor.owl_intuition_electricity_radio:
      friendly_name: Owl Signal

    sensor.owl_intuition_electricity_power:
      friendly_name: Electricity Using
    sensor.owl_intuition_electricity_today:
      friendly_name: Electricity Used Today
    sensor.owl_intuition_cost_today:
      friendly_name: Electricity Cost Today

    sensor.owl_intuition_solar_generating:
      friendly_name: Solar Generating
    sensor.owl_intuition_solar_exporting:
      friendly_name: Solar Exporting
    sensor.owl_intuition_solar_generated_today:
      friendly_name: Solar Generated Today
    sensor.owl_intuition_solar_exported_today:
      friendly_name: Solar Exported Today

##################################################
## Components/Sensors
##################################################
sensor:
  - platform: owlintuition
    host: 192.168.200.45
    port: 32000
    mode: triphase
    cost_icon: 'mdi:currency-gbp'
    cost_unit_of_measurement: GBP
    monitored_conditions:
      - electricity
      - solar

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.owl_intuition_electricity_power
      - sensor.owl_intuition_electricity_today
      - sensor.owl_intuition_cost_today
      - sensor.owl_intuition_solar_generating
      - sensor.owl_intuition_solar_exporting
      - sensor.owl_intuition_solar_generated_today
      - sensor.owl_intuition_solar_exported_today

history:
  include:
    entities:
      - sensor.owl_intuition_electricity_power
      - sensor.owl_intuition_electricity_today
      - sensor.owl_intuition_cost_today
      - sensor.owl_intuition_solar_generating
      - sensor.owl_intuition_solar_exporting
      - sensor.owl_intuition_solar_generated_today
      - sensor.owl_intuition_solar_exported_today