#################################################
# Components/Sensors
#################################################

ring:
  # https://www.home-assistant.io/components/ring/
  username: !secret ring_username
  password: !secret ring_password

camera:
  - platform: ring

sensor:
  - platform: ring

switch:
  - platform: ring

light:
  - platform: ring

