##################################################
## Components/Sensors
##################################################
ios:
  push:
    categories:
      - name: late_night_tv_alert
        identifier: 'TVALARM'
        actions:
          - identifier: PLAY_LATE_TV_MESSAGE
            title: 'Play Message?'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - media_player.frasertv
      - media_player.ironing_room_tv
      - media_player.living_room_tv
      - switch.lwrf_loft_fraser_tv
history:
  include:
      entities:
      - media_player.frasertv
      - media_player.ironing_room_tv
      - media_player.living_room_tv
      - switch.lwrf_loft_fraser_tv

##################################################
## Automation
##################################################
automation:
  - alias: Turn off Frasers TV if on after curfew
    trigger:
      platform: state
      entity_id: media_player.frasertv
      to: 'on'
      for:
        minutes: 6
    condition:
      condition: time
      after: '22:00:00'
      before: '06:59:00'
    action:
      - service: notify.mobile_app_martin_iphonexs
        data:
          message: "Turning off Frasers TV"
          data: 
            push:
              category: tvalarm
      - service: homeassistant.turn_off
        entity_id: media_player.frasertv

  - alias: Sonos TTS Warning Late TV
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: PLAY_LATE_TV_MESSAGE
    action:
      service: script.sonos_say
      data:
        sonos_entity: media_player.frasers_room
        volume: 0.5
        message: "Turn off your TV and go to sleep"
        # Delay needs to be long enough to allow text to be read aloud
        delay: "00:00:05"

  - alias: Turn off power to Frasers TV if on 1hr after curfew
    trigger:
      platform: state
      entity_id: media_player.frasertv
      to: 'on'
      for:
        minutes: 5
    condition:
      condition: time
      after: '22:30:00'
      before: '06:59:00'
    action:
      - service: notify.mobile_app_martin_iphonexs
        data:
          message: "Cutting power to Fraser's TV"
          data: 
            push:
              category: tvalarm
      - service: homeassistant.turn_off
        entity_id: switch.lwrf_loft_fraser_tv

  - alias: Restore power to Frasers TV
    trigger:
      - platform: time
        at: "07:00:00"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.lwrf_loft_fraser_tv
